apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/full-stack-6db76/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://username:password@postgres:5432/mydatabase"

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend
  type: ClusterIP
